version: 0.0
os: linux

files:
  - source: /
    destination: /opt/ci-pipeline-demo/releases/release-${DEPLOYMENT_ID}

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/load-image.sh
      timeout: 300
      runas: ubuntu

    - location: scripts/switch-symlink.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
